modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Ender-Tendril/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ender-tendril"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512"

[[mods]]
    modId="endertendril"
    version="${file.jarVersion}"
    displayName="Ender Tendril"
    #updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Ender-Tendril/1.16.x/update.json"
    description='''
    Growable ender pearl substitutes
    '''

[[dependencies.endertendril]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.endertendril]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.endertendril]]
    modId="silentlib"
    mandatory=false
    versionRange="[8,9)"
    ordering="NONE"
    side="BOTH"
